version: '2'
volumes:
  movies:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.3
      export: /data/Videos/films
      onRemove: retain
  series:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.3
      export: /data/Videos/Series
      onRemove: retain
  music:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.3
      export: /data/Music
      onRemove: retain
  sabnzbd_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/sabnzbd
      onRemove: retain
  sabnzbd_complete:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/complete
      onRemove: retain
  sabnzbd_incomplete:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/incomplete
      onRemove: retain
  couchpotato_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/couchpotato
      onRemove: retain
  couchpotato_download:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/complete/movies
      onRemove: retain
  sickrage_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/sickrage
      onRemove: retain
  sickrage_download:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/complete/tv
      onRemove: retain
  radarr_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/radarr
      onRemove: retain
  radarr_download:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/complete/movies_radarr
      onRemove: retain
  sonarr_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/sonarr
      onRemove: retain
  sonarr_download:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /download/complete/tv_sonarr
      onRemove: retain
  plex_config:
    driver: rancher-nfs
    driver_opts:
      host: 192.168.1.23
      export: /apps/plex
      onRemove: retain

services:
    couchpotato:
        image: linuxserver/couchpotato:latest
        ports:
            - 5000:5000/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - couchpotato_config:/config
            - movies:/movies
            - couchpotato_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sickrage:
        image: linuxserver/sickrage:latest
        ports:
            - 5001:5001/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sickrage_config:/config
            - movies:/movies
            - sickrage_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sonarr:
        image: linuxserver/sonarr:latest
        ports:
            - 5002:5002/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sonarr_config:/config
            - movies:/movies
            - sonarr_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    radarr:
        image: linuxserver/radarr:latest
        ports:
            - 5003:5003/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - radarr_config:/config
            - movies:/movies
            - radarr_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sabnzbd:
        image: linuxserver/sabnzbd:latest
        ports:
            - 5004:8080/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sabnzbd_complete:/downloads
            - sabnzbd_incomplete:/incomplete-downloads
            - sabnzbd_config:/config
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
