version: '2'
volumes:
  movies:
    driver: rancher-nfs
    driver_opts:
      host: ${TARGET_NFS}
      export: ${MOVIE_SHARE}
      onRemove: retain
  series:
    driver: rancher-nfs
    driver_opts:
      host: ${TARGET_NFS}
      export: ${TV_SHARE}
      onRemove: retain
  sabnzbd_config:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${APP_ROOT_DIR}/sabnzbd
      onRemove: retain
  sabnzbd_complete:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_COMPLETE_DIR}
      onRemove: retain
  sabnzbd_incomplete:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_INCOMPLETE_DIR}
      onRemove: retain
  couchpotato_config:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${APP_ROOT_DIR}/couchpotato
      onRemove: retain
  couchpotato_download:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_COMPLETE_DIR}/movies
      onRemove: retain
  sickrage_config:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${APP_ROOT_DIR}/sickrage
      onRemove: retain
  sickrage_download:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_COMPLETE_DIR}/tv
      onRemove: retain
  radarr_config:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${APP_ROOT_DIR}/radarr
      onRemove: retain
  radarr_download:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_COMPLETE_DIR}/movies_radarr
      onRemove: retain
  sonarr_config:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${APP_ROOT_DIR}/sonarr
      onRemove: retain
  sonarr_download:
    driver: rancher-nfs
    driver_opts:
      host: ${APP_NFS}
      export: ${SABNZBD_COMPLETE_DIR}/tv_sonarr
      onRemove: retain

services:
    couchpotato:
        image: linuxserver/couchpotato:latest
        ports:
            - ${COUCHPOTATO_PORT}:${COUCHPOTATO_PORT}/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - couchpotato_config:/config
            - movies:/movies
            - couchpotato_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sickrage:
        image: linuxserver/sickrage:latest
        ports:
            - ${SICKRAGE_PORT}:${SICKRAGE_PORT}/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sickrage_config:/config
            - series:/tv
            - sickrage_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sonarr:
        image: linuxserver/sonarr:latest
        ports:
            - ${SONARR_PORT}:${SONARR_PORT}/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sonarr_config:/config
            - series:/tv
            - sonarr_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    radarr:
        image: linuxserver/radarr:latest
        ports:
            - ${RADARR_PORT}:${RADARR_PORT}/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - radarr_config:/config
            - movies:/movies
            - radarr_download:/downloads
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
    sabnzbd:
        image: linuxserver/sabnzbd:latest
        ports:
            - ${SABNZBD_PORT}:8080/tcp
        environment:
            PUID: 1001
            GUID: 1001
            TZ: Europe/Paris
        volumes:
            - sabnzbd_complete:/downloads
            - sabnzbd_incomplete:/incomplete-downloads
            - sabnzbd_config:/config
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
